### ISSUE TITLE
trades stopped populating

### ISSUE THREAD

**Issue by poop-poop-poop** [Rudokhvist/ASF-STM#28]
yesterday everything worked fine for me, but today the trades won't populate?

I tried clearing browser data, and I re-started the scan over and over, but I'm getting the same behavior (matching seems fine, clicking the "offer a trade" button brings up the trade window as expected, but nothing populates)

**Comment by Rudokhvist** [comment]
I just merged my last changes that does a lot of changes to population algorithm. It will probably take some time for greasyfork to sync and send an update to users, but after it's updated to 4.1 you can check if you issue gets resolved with it too.
