### ISSUE TITLE
stopped working today

### ISSUE THREAD

**Issue by catharsis71** [Rudokhvist/ASF-STM#29]
starting earlier today, pressing the "Scan ASF STM" button causes it to grey out with nothing else happening.  Checked console output & nothing there.

**Comment by Rudokhvist** [comment]
It's not for the first time I see people reporting such issue (which strangely resolves itself in a day or two), but so far I was unable to reproduce it. What browser and userscript extension are you using?

**Comment by catharsis71** [comment]
Well it's working again now.

for reference I'm on Firefox ESR 128.1.0, using Greasemonkey

If it happens again is there any information I should grab while the problem is happening?
